/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame.Proje;

import static JFrame.Proje.Register.connect;
import static JFrame.Proje.Register.password;
import static JFrame.Proje.Register.username;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author firat
 */
public class Login extends javax.swing.JFrame {
public static final String username = "root";
    public static final String password = "sundayman";
    public static final String connect = "jdbc:mysql://localhost:3306/users";
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPopupMenu1 = new javax.swing.JPopupMenu();
        pop_quit = new javax.swing.JMenuItem();
        pop_max = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        j_login_email = new javax.swing.JTextField();
        j_login_password = new javax.swing.JPasswordField();
        j_bt_login = new javax.swing.JButton();
        j_bt_reset = new javax.swing.JButton();
        j_bt_register = new javax.swing.JButton();
        about_bt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        jPopupMenu1.setComponentPopupMenu(jPopupMenu1);

        pop_quit.setText("Quit");
        pop_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pop_quitActionPerformed(evt);
            }
        });
        jPopupMenu1.add(pop_quit);

        pop_max.setText("maximize");
        pop_max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pop_maxActionPerformed(evt);
            }
        });
        jPopupMenu1.add(pop_max);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setComponentPopupMenu(jPopupMenu1);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("LOGIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(58, 23, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("E-Mail:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 84, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 58, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 147;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 18, 0, 0);
        jPanel1.add(j_login_email, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 147;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 18, 0, 0);
        jPanel1.add(j_login_password, gridBagConstraints);

        j_bt_login.setText("Login");
        j_bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_bt_loginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(59, 0, 0, 0);
        jPanel1.add(j_bt_login, gridBagConstraints);

        j_bt_reset.setText("Reset");
        j_bt_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_bt_resetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(59, 7, 0, 0);
        jPanel1.add(j_bt_reset, gridBagConstraints);

        j_bt_register.setText("Register Page");
        j_bt_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_bt_registerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(59, 18, 0, 0);
        jPanel1.add(j_bt_register, gridBagConstraints);

        about_bt.setText("About System");
        about_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_btActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(59, 29, 0, 10);
        jPanel1.add(about_bt, gridBagConstraints);

        jButton1.setText("Forgot Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(59, 6, 0, 0);
        jPanel1.add(jButton1, gridBagConstraints);

        getContentPane().add(jPanel1);

        jMenu2.setText("What you doing here?");

        jMenuItem1.setText("Get Info");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jCheckBoxMenuItem1.setText("You still don't sign up?");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Welcome to the system of tracking live species classes. If you already sign up just login.");
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxMenuItem1.isSelected()){
                    JOptionPane.showMessageDialog(null,"Go register page");

            
            
        }
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed
    //register sayfasına git
    private void j_bt_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_bt_registerActionPerformed
        // TODO add your handling code here:
        
        Register register_frame = new Register();
        register_frame.show();
        dispose();
        
    }//GEN-LAST:event_j_bt_registerActionPerformed
//email password alanlarını sıfırla
    private void j_bt_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_bt_resetActionPerformed
        // TODO add your handling code here:
        j_login_email.setText("");
        j_login_password.setText("");
    }//GEN-LAST:event_j_bt_resetActionPerformed
//Programdan çık
    private void pop_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pop_quitActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, 
                "Confirm if you want to exit", "Are you sure",JOptionPane.YES_NO_OPTION);
        if (input == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_pop_quitActionPerformed
    //Pencereyi maksiumum boyuta getir
    private void pop_maxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pop_maxActionPerformed
        // TODO add your handling code here:
        JFrame my_frame = new JFrame();
        setExtendedState(my_frame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_pop_maxActionPerformed
    // AboutUs Sayfasına git
    private void about_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_btActionPerformed
            // TODO add your handling code here:
        AboutUs about = new AboutUs();
        about.show();
        dispose();
    }//GEN-LAST:event_about_btActionPerformed

    // email ile password databasede bulunuyorsa table sayasına git,yoksa hata mesajı ver
    private void j_bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_bt_loginActionPerformed
    try {
        // TODO add your handling code here:
        
        sqlConn = DriverManager.getConnection(connect, username, password);
        
        String query = "select * from users.users_table where E_mail= ? AND Password = ?";
         pst = (PreparedStatement) sqlConn.prepareStatement(query);
         pst.setString(1,j_login_email.getText() );
         
         pst.setString(2,String.valueOf(j_login_password.getPassword()));
           rs = pst.executeQuery();
          if (rs.next() == false){
            JOptionPane.showMessageDialog(null, "Username or Password is wrong");
        }
        else
        {
            Tables tables = new Tables();
            tables.show();
            dispose();
        }
    } catch (Exception ex ) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        
    }
    
                    
   
    }//GEN-LAST:event_j_bt_loginActionPerformed
    //Şifre Değiştirme ekranına git
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Change_Password ch = new Change_Password();
            ch.show();
            dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton about_bt;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JButton j_bt_login;
    private javax.swing.JButton j_bt_register;
    private javax.swing.JButton j_bt_reset;
    private javax.swing.JTextField j_login_email;
    private javax.swing.JPasswordField j_login_password;
    private javax.swing.JMenuItem pop_max;
    private javax.swing.JMenuItem pop_quit;
    // End of variables declaration//GEN-END:variables
}
