/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame.Proje;

import static JFrame.Proje.Login.connect;
import static JFrame.Proje.Login.password;
import static JFrame.Proje.Login.username;
import static JFrame.Proje.Tables.connect;
import static JFrame.Proje.Tables.password;
import static JFrame.Proje.Tables.username;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author firat
 */
public class Register extends javax.swing.JFrame {

    public static final String username = "root";
    public static final String password = "sundayman";
    public static final String connect = "jdbc:mysql://localhost:3306/users";
    Connection sqlConn = null;
    PreparedStatement pst = null;

    ResultSet rs = null;
    Statement st = null;
    ArrayList<String> email = new ArrayList<String>();

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();

    }

    //User classını oluştur
    class User {

        String name_surname;
        String email;
        int age;
        String proffesion;
        String student;
        String password;
        String rpassword;

        public String getName_surname() {
            return name_surname;
        }

        public void setName_surname(String name_surname) {
            this.name_surname = name_surname;
        }

        public String getEmail() {
            return email;
        }

        public void setEmail(String email) {
            this.email = email;
        }

        public int getAge() {
            return age;
        }

        public void setAge(int age) {
            this.age = age;
        }

        public String getProffesion() {
            return proffesion;
        }

        public void setProffesion(String proffesion) {
            this.proffesion = proffesion;
        }

        public String getStudent() {
            return student;
        }

        public void setStudent(String student) {
            this.student = student;
        }

        public String getPassword() {
            return password;
        }

        public void setPassword(String password) {
            this.password = password;
        }

        public String getRpassword() {
            return rpassword;
        }

        public void setRpassword(String rpassword) {
            this.rpassword = rpassword;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPopupMenu1 = new javax.swing.JPopupMenu();
        r_exit = new javax.swing.JMenuItem();
        r_max = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        j_register_name = new javax.swing.JTextField();
        j_register_mail = new javax.swing.JTextField();
        j_register_age = new javax.swing.JSpinner();
        j_register_password = new javax.swing.JPasswordField();
        j_register_rpassword = new javax.swing.JPasswordField();
        j_register_check = new javax.swing.JCheckBox();
        j_register_combo = new javax.swing.JComboBox<>();
        reset_bt = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        register_bt = new javax.swing.JButton();
        loginpage_bt = new javax.swing.JButton();

        r_exit.setText("Quit");
        r_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_exitActionPerformed(evt);
            }
        });
        jPopupMenu1.add(r_exit);

        r_max.setText("Maximize");
        r_max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_maxActionPerformed(evt);
            }
        });
        jPopupMenu1.add(r_max);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setComponentPopupMenu(jPopupMenu1);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Register");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(61, 71, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name Surname:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(61, 112, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("E-Mail:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 30, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Age:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 44, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 3, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Password Confirmation:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 51, 0, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        j_register_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                j_register_nameKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 122;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(61, 1, 0, 0);
        jPanel1.add(j_register_name, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 122;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 1, 0, 0);
        jPanel1.add(j_register_mail, gridBagConstraints);

        j_register_age.setModel(new javax.swing.SpinnerNumberModel(10, 10, 100, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 1, 0, 0);
        jPanel1.add(j_register_age, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 105;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        jPanel1.add(j_register_password, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 105;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 0, 0, 0);
        jPanel1.add(j_register_rpassword, gridBagConstraints);

        j_register_check.setBackground(new java.awt.Color(255, 153, 0));
        j_register_check.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j_register_check.setText("Student");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 140, 0, 0);
        jPanel1.add(j_register_check, gridBagConstraints);

        j_register_combo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j_register_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biologist", "Genetic counselor", "Biomedical Scientist", "Laboratory Technician", "Biomedical Engineer", "Microbiologist", "Teacher", "Environmental scientist", "Biomedical scientist", "Plant Biologist", "Biochemist", "Other" }));
        j_register_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_register_comboActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 30;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -38;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 14, 0, 0);
        jPanel1.add(j_register_combo, gridBagConstraints);

        reset_bt.setText("Reset");
        reset_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(53, 54, 111, 0);
        jPanel1.add(reset_bt, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Profession:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 140, 0, 0);
        jPanel1.add(jLabel7, gridBagConstraints);

        register_bt.setText("Register");
        register_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_btActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(53, 51, 111, 0);
        jPanel1.add(register_bt, gridBagConstraints);

        loginpage_bt.setText("Login Page");
        loginpage_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginpage_btActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 31;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(53, 17, 111, 85);
        jPanel1.add(loginpage_bt, gridBagConstraints);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Login sayfasına git
    private void loginpage_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginpage_btActionPerformed
        // TODO add your handling code here:
        Login login_frame = new Login();
        login_frame.show();
        dispose();

    }//GEN-LAST:event_loginpage_btActionPerformed
//Pencereyi maksiumum boyuta getir
    private void r_maxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_maxActionPerformed
        // TODO add your handling code here:
        JFrame my2_frame = new JFrame();
        setExtendedState(my2_frame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_r_maxActionPerformed
//Çıkış yap
    private void r_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_exitActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null,
                "Confirm if you want to exit", "Are you sure", JOptionPane.YES_NO_OPTION);
        if (input == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_r_exitActionPerformed

    private void j_register_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_register_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_register_comboActionPerformed
    //Bİlgileri sıfırla
    private void reset_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btActionPerformed
        // TODO add your handling code here:
        j_register_name.setText("");
        j_register_mail.setText("");
        j_register_check.setSelected(false);
        j_register_combo.setSelectedIndex(0);
        j_register_password.setText("");
        j_register_rpassword.setText("");

        j_register_age.setValue(10);
    }//GEN-LAST:event_reset_btActionPerformed

    private void register_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_btActionPerformed
        // Regex format kontrolu

        String name_pattern = "[a-zA-z\\s]+";
        String number_pattern = "^[0-9]*$";
        String email_pattern = "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$";

        Pattern pattern = Pattern.compile(name_pattern);
        Pattern pattern2 = Pattern.compile(number_pattern);
        Pattern pattern3 = Pattern.compile(email_pattern);

        Matcher regexmatcher = pattern.matcher(j_register_name.getText());
        Matcher regexmatcher2 = pattern2.matcher(String.valueOf(j_register_password.getPassword()));
        Matcher regexmatcher3 = pattern3.matcher(j_register_mail.getText());
        //Regex sonucuna göre hata mesajı
        if (!(regexmatcher.matches())) {
            JOptionPane.showMessageDialog(null, "Only Letters!", "Wrong Name Format", JOptionPane.ERROR_MESSAGE);

        } else if (!(regexmatcher2.matches())) {
            JOptionPane.showMessageDialog(null, "Only Numbers!", "Wrong Password Format", JOptionPane.ERROR_MESSAGE);

        } else if (!(regexmatcher3.matches())) {
            JOptionPane.showMessageDialog(null, "Email format is not correct!", "Wrong Email Format", JOptionPane.ERROR_MESSAGE);

        } else if (j_register_name.getText().equals("") || j_register_mail.getText().equals("") || j_register_password.getPassword().equals("") || j_register_rpassword.getPassword().equals("")) {
            JOptionPane.showMessageDialog(null, "Fill all area", "Fill!", JOptionPane.ERROR_MESSAGE);
        } else {
            //Şifreler aynı olup olmadığı kontrolü
            if (!(Arrays.equals(j_register_password.getPassword(), j_register_rpassword.getPassword()))) {
                JOptionPane.showMessageDialog(null, "Passwords are not same", "Check Password!", JOptionPane.ERROR_MESSAGE);

            } else {
                //Email önceden kullanılmışsa hata ver yoksa kayıt ol
//                String text = j_register_mail.getText();
//                String query2 = "select E_mail from users.users_table where E_mail= ? ";
//                try {
//
//                    sqlConn = DriverManager.getConnection(connect, username, password);
//                    System.out.println("Bağlandı");
//                    PreparedStatement pst2 = sqlConn.prepareStatement(query2);
//                    pst2.setString(1, text);
//                    ResultSet rs2 = pst.executeQuery();
//                    
//                    if (rs2.next()) {
//                        JOptionPane.showMessageDialog(null, "This E-mail Already Used!");
//                    }
//                } catch (SQLException ex) {
//                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
//                }
//
//                User u = new User();
//                u.setName_surname(j_register_name.getText());
//                u.setEmail(j_register_mail.getText());
//                u.setAge((int) j_register_age.getValue());
//                u.setProffesion((String) j_register_combo.getSelectedItem());
//                if (j_register_check.isSelected()) {
//                    u.student = "Student";
//                } else {
//                    u.student = "Not Student";
//                }
//                u.setPassword(String.valueOf(j_register_password.getPassword()));
//
//                try {
//                    {
//
////                    if (check_email(u.getEmail())) {
//                        String query = "insert into users_table (Name_surname,E_mail,Age,Profession,Student,Password)"
//                                + " values (?,?,?,?,?,?)";
//                        pst = sqlConn.prepareStatement(query);
//
//                        pst.setString(1, u.getName_surname());
//                        pst.setString(2, u.getEmail());
//                        pst.setInt(3, u.getAge());
//                        pst.setString(4, u.getProffesion());
//                        pst.setString(5, u.getStudent());
//                        pst.setString(6, u.getPassword());
//                        pst.executeUpdate();
//                        JOptionPane.showMessageDialog(null, "You signed up");
//
//                    }
//
//                } catch (SQLException ex) {
//
//                }
//                catch (SQLIntegrityConstraintViolationException ex) {
//                    
//                }

                User u = new User();
                u.setName_surname(j_register_name.getText());
                u.setEmail(j_register_mail.getText().trim());
                u.setAge((int) j_register_age.getValue());
                u.setProffesion((String) j_register_combo.getSelectedItem());
                if (j_register_check.isSelected()) {
                    u.student = "Student";
                } else {
                    u.student = "Not Student";
                }
                u.setPassword(String.valueOf(j_register_password.getPassword()));

                try {
                    {

//                    
                        sqlConn = DriverManager.getConnection(connect, username, password);
                        String query = "insert into users_table (Name_surname,E_mail,Age,Profession,Student,Password)"
                                + " values (?,?,?,?,?,?)";
                        pst = sqlConn.prepareStatement(query);

                        pst.setString(1, u.getName_surname());
                        pst.setString(2, u.getEmail());
                        pst.setInt(3, u.getAge());
                        pst.setString(4, u.getProffesion());
                        pst.setString(5, u.getStudent());
                        pst.setString(6, u.getPassword());
                        pst.executeUpdate();
                         JOptionPane.showMessageDialog(rootPane,"You signed up");        
//                        String getEmail = "Select E_mail from users.users_table";
//                        Statement pst_email = sqlConn.createStatement();
//                        ResultSet rs_email = pst_email.executeQuery(getEmail);
                        
                    }

//                    for (String string : email) {
//                        
//                        if (u.getEmail().equals(string)) {
//                            JOptionPane.showMessageDialog(rootPane, "Hata");
//                            break;
//                        }
//                        else
//                        {
//                       
//                        pst.executeUpdate();
//                        break;
//                        }
//                        
//                    }
                } catch (SQLException ex) {

                }
            }
        }


    }//GEN-LAST:event_register_btActionPerformed

    private void j_register_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_j_register_nameKeyPressed

        // TODO add your handling code here:

    }//GEN-LAST:event_j_register_nameKeyPressed
//    public boolean check_email(String username) throws SQLException, ClassNotFoundException {
//
//        boolean e_mail = true;
//        String query = "select * from 'users_table' where 'E_mail'= '?'";
//        try {
//
//            PreparedStatement pst2 = sqlConn.prepareStatement(query);
//            pst2.setString(1, j_register_mail.getText());
//            ResultSet rs2 = pst2.executeQuery();
//            if (rs2.next()) {
//                e_mail = false;
//                JOptionPane.showMessageDialog(null, "You have already account.");
//            }
//
//        } catch (SQLException ex) {
//            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//        return e_mail;
//
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSpinner j_register_age;
    private javax.swing.JCheckBox j_register_check;
    private javax.swing.JComboBox<String> j_register_combo;
    private javax.swing.JTextField j_register_mail;
    private javax.swing.JTextField j_register_name;
    private javax.swing.JPasswordField j_register_password;
    private javax.swing.JPasswordField j_register_rpassword;
    private javax.swing.JButton loginpage_bt;
    private javax.swing.JMenuItem r_exit;
    private javax.swing.JMenuItem r_max;
    private javax.swing.JButton register_bt;
    private javax.swing.JButton reset_bt;
    // End of variables declaration//GEN-END:variables
}
